# .github/workflows/update-pr-title.yml
name: Update PR Title

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR title using GitHub API
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Extract the branch name from the head ref
            const branch = context.payload.pull_request.head.ref.split('/');
            
            // If the branch doesn't follow the expected format (type/subtype), assume it's a generated branch
            const expectedBranchPrefix = branch.length > 1 ? `${branch[0]}(${branch[1]}): ` : 'generated(bot): ';

            if (context.payload.pull_request.title.startsWith(expectedBranchPrefix)) {
              console.log('PR title already starts with the expected prefix. No update needed.');
              return;
            }
            
            // Get commits on the PR to find the first commit
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 1
            });
            
            // Get the first commit message - the first item in the array is the earliest commit
            const firstCommit = commits.data.length > 0 ? commits.data[0] : null;
            const commitMessage = firstCommit ? firstCommit.commit.message.split('\n')[0] : context.payload.pull_request.title;
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: expectedBranchPrefix + commitMessage,
            })